# Generated by Django 5.0.3 on 2024-03-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productincart',
            name='summ',
            field=models.IntegerField(default=0, verbose_name='цена товаров'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='total_sum',
            field=models.IntegerField(default=0, verbose_name='цена всех товаров'),
            preserve_default=False,
        ),
    ]
