# Generated by Django 5.0.3 on 2024-03-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_carts', '0002_productincart_summ_shoppingcart_total_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productincart',
            name='summ',
            field=models.IntegerField(default=0, verbose_name='цена товаров'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='total_sum',
            field=models.IntegerField(default=0, verbose_name='цена всех товаров'),
        ),
    ]
