# Generated by Django 5.0.3 on 2024-03-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_carts', '0003_alter_productincart_summ_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productincart',
            name='count',
            field=models.IntegerField(default=0, verbose_name='количество в корзине'),
        ),
    ]
