# Generated by Django 5.0.3 on 2024-03-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_carts', '0004_alter_productincart_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productincart',
            options={'verbose_name': 'товар в корзине', 'verbose_name_plural': 'товары в корзине'},
        ),
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'verbose_name': 'корзина', 'verbose_name_plural': 'корзины'},
        ),
        migrations.AlterField(
            model_name='productincart',
            name='summ',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='цена товаров'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='total_sum',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='цена всех товаров'),
        ),
    ]
