# Generated by Django 5.0.3 on 2024-03-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_carts', '0005_alter_productincart_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productincart',
            name='summ',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='цена товаров'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='total_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='цена всех товаров'),
        ),
    ]
